//! Codegen for `crab-world/src/bot/rig/baked.rs`: the committed fitted-collider table
//! the runtime consumes instead of fitting at spawn (bddap/rl#20 Phase 2). Floats are
//! emitted with Rust's shortest-roundtrip formatting, so the generated literals parse
//! back to bit-identical values — the bake is exact, not approximate.

use std::fmt::Write as _;

use bevy::prelude::*;
use crab_world::bot::body::{CrabJointId, Side};
use crab_world::bot::rig::{LinkShape, PartId, RigLink, RigRecipe, arc_to};

use crate::fit::fit_capsule;
use crate::gltf_load::LoadedModel;

/// The fitted recipe: `rig::build_recipe`'s bone-chain skeleton with each link's
/// collider geometry replaced by the principal-axis capsule fit of its skinned vertex
/// cloud (≥ 8 points; smaller/missing clouds keep the bone-chain stub). This is the
/// fit that used to run at every spawn (pre-rl#277 revert re-land); it now runs only
/// here, at bake time.
pub fn fitted_recipe(model: &LoadedModel) -> Option<RigRecipe> {
    let mut recipe = crab_world::bot::rig::build_recipe(model)?;
    let clouds = model.vertices_by_part();
    for link in &mut recipe.links {
        let Some(id) = link.actuated else {
            continue;
        };
        let Some(pts) = clouds.get(&PartId::Joint(id)) else {
            continue;
        };
        if pts.len() < 8 {
            continue;
        }
        let Some(cap) = fit_capsule(pts) else {
            continue;
        };
        let origin = model
            .bone_origin(&link.bone)
            .expect("build_recipe only emits links whose pivot bone exists");
        let seg = cap.b - cap.a;
        link.center = (cap.a + cap.b) * 0.5 - origin;
        link.col_rot = arc_to(Vec3::Y, seg);
        link.shape = LinkShape::Capsule {
            half_height: seg.length() * 0.5,
            radius: cap.radius,
        };
    }
    Some(recipe)
}

fn f(x: f32) -> String {
    assert!(x.is_finite(), "non-finite value in the fitted recipe: {x}");
    format!("{x:?}")
}

fn vec3(v: Vec3) -> String {
    format!("Vec3::new({}, {}, {})", f(v.x), f(v.y), f(v.z))
}

fn quat(q: Quat) -> String {
    format!(
        "Quat::from_xyzw({}, {}, {}, {})",
        f(q.x),
        f(q.y),
        f(q.z),
        f(q.w)
    )
}

fn side(s: Side) -> &'static str {
    match s {
        Side::Left => "Side::Left",
        Side::Right => "Side::Right",
    }
}

fn joint(id: CrabJointId) -> String {
    use CrabJointId::*;
    match id {
        LegCoxa(s, n) => format!("CrabJointId::LegCoxa({}, {n})", side(s)),
        LegBasis(s, n) => format!("CrabJointId::LegBasis({}, {n})", side(s)),
        LegMerus(s, n) => format!("CrabJointId::LegMerus({}, {n})", side(s)),
        LegCarpus(s, n) => format!("CrabJointId::LegCarpus({}, {n})", side(s)),
        ClawShoulder(s) => format!("CrabJointId::ClawShoulder({})", side(s)),
        ClawWrist(s) => format!("CrabJointId::ClawWrist({})", side(s)),
        ClawPincer(s) => format!("CrabJointId::ClawPincer({})", side(s)),
    }
}

fn shape(s: LinkShape) -> String {
    match s {
        LinkShape::Capsule {
            half_height,
            radius,
        } => format!(
            "LinkShape::Capsule {{ half_height: {}, radius: {} }}",
            f(half_height),
            f(radius)
        ),
        LinkShape::Cuboid { half } => format!("LinkShape::Cuboid {{ half: {} }}", vec3(half)),
    }
}

fn push_link(out: &mut String, l: &RigLink) {
    let parent = match l.parent {
        None => "None".to_string(),
        Some(i) => format!("Some({i})"),
    };
    let actuated = match l.actuated {
        None => "None".to_string(),
        Some(id) => format!("Some({})", joint(id)),
    };
    let _ = write!(
        out,
        "            RigLink {{\n                bone: {:?}.to_string(),\n                parent: {parent},\n                anchor1: {},\n                axis_local: {},\n                shape: {},\n                center: {},\n                col_rot: {},\n                density: {},\n                actuated: {actuated},\n            }},\n",
        l.bone,
        vec3(l.anchor1),
        vec3(l.axis_local),
        shape(l.shape),
        vec3(l.center),
        quat(l.col_rot),
        f(l.density),
    );
}

pub fn render_baked_rs(recipe: &RigRecipe, asset_digest: u64) -> String {
    let mut out = format!(
        "//! GENERATED by `cargo run -p meshfit -- bake` — DO NOT EDIT (bddap/rl#20).\n\
         //!\n\
         //! The committed fitted-collider table: THE one source of Sally's collider\n\
         //! geometry at runtime. Baked offline from sally.glb (FNV-1a/64\n\
         //! {asset_digest:#018x}); [`crate::mesh_fallback`] refuses any asset whose\n\
         //! digest disagrees, so a sally.glb change is loud and a re-bake is a\n\
         //! deliberate, reviewed diff of this file. Any geometry change here is a NEW\n\
         //! MDP: live checkpoints cannot drive it — plan a retrain (rl#277). A re-bake\n\
         //! must ship with the new sally.glb under a NEW rl-assets release tag (plus\n\
         //! the scripts/fetch-sally.sh bump) in the same commit — clobbering the old\n\
         //! tag strands every deployed binary on the refusal path.\n\n\
         use bevy::prelude::*;\n\n\
         use crate::bot::body::{{CrabJointId, Side}};\n\n\
         use super::{{LinkShape, RigLink, RigRecipe}};\n\n\
         /// FNV-1a/64 of the exact sally.glb bytes this table was fitted from.\n\
         pub const BAKED_ASSET_DIGEST: u64 = {asset_digest:#018x};\n\n\
         #[rustfmt::skip]\n\
         pub fn baked_recipe() -> RigRecipe {{\n    RigRecipe {{\n"
    );
    let _ = write!(
        out,
        "        hub_bind_world: {},\n        carapace_half: {},\n        carapace_offset: {},\n        carapace_density: {},\n",
        vec3(recipe.hub_bind_world),
        vec3(recipe.carapace_half),
        vec3(recipe.carapace_offset),
        f(recipe.carapace_density),
    );
    out.push_str("        links: vec![\n");
    for l in &recipe.links {
        push_link(&mut out, l);
    }
    out.push_str("        ],\n    }\n}\n");
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crab_world::bot::rig::{BAKED_ASSET_DIGEST, baked_recipe};
    use crab_world::mesh_fallback::model_path;

    /// THE fitted-vs-committed drift-guard (bddap/rl#20 Phase 0's promise, Phase 2's
    /// teeth): a re-fit of the canonical asset must reproduce the committed baked
    /// table BIT-EXACTLY. Red means either the fitter changed (deliberate → re-bake,
    /// review the geometry diff, plan a retrain) or the bake is stale. Skips without
    /// the model; hard-fails on an asset-digest mismatch (that's a sally.glb change —
    /// re-bake deliberately, never re-baseline blind).
    #[test]
    fn baked_matches_refit() {
        let Some(path) = model_path() else {
            eprintln!("baked_matches_refit: no model — skipping");
            return;
        };
        let bytes = std::fs::read(&path).expect("read model");
        let digest = crab_world::fnv::fnv1a(&bytes);
        assert_eq!(
            digest, BAKED_ASSET_DIGEST,
            "sally.glb changed (digest {digest:#018x} != baked {BAKED_ASSET_DIGEST:#018x}) — \
             run `cargo run -p meshfit -- bake`, review the geometry diff, expect a retrain"
        );
        let model = LoadedModel::from_slice(&bytes).expect("load model");
        let refit = fitted_recipe(&model).expect("fitted recipe");
        let baked = baked_recipe();

        assert_eq!(refit.hub_bind_world, baked.hub_bind_world, "hub_bind_world");
        assert_eq!(refit.carapace_half, baked.carapace_half, "carapace_half");
        assert_eq!(
            refit.carapace_offset, baked.carapace_offset,
            "carapace_offset"
        );
        assert_eq!(
            refit.carapace_density, baked.carapace_density,
            "carapace_density"
        );
        assert_eq!(refit.links.len(), baked.links.len(), "link count");
        for (i, (r, b)) in refit.links.iter().zip(&baked.links).enumerate() {
            assert_eq!(r.bone, b.bone, "link {i}: bone");
            assert_eq!(r.parent, b.parent, "link {i} ({}): parent", r.bone);
            assert_eq!(r.actuated, b.actuated, "link {i} ({}): actuated", r.bone);
            assert_eq!(r.anchor1, b.anchor1, "link {i} ({}): anchor1", r.bone);
            assert_eq!(
                r.axis_local, b.axis_local,
                "link {i} ({}): axis_local",
                r.bone
            );
            assert_eq!(r.shape, b.shape, "link {i} ({}): shape", r.bone);
            assert_eq!(r.center, b.center, "link {i} ({}): center", r.bone);
            assert_eq!(r.col_rot, b.col_rot, "link {i} ({}): col_rot", r.bone);
            assert_eq!(r.density, b.density, "link {i} ({}): density", r.bone);
        }
    }

    /// Every Def_/Ctrl_ bone in the model must map to a physics part, or its flesh
    /// silently fits into nothing (moved from the old runtime meshfit tests).
    #[test]
    fn bone_map_covers_all_model_bones() {
        let Some(path) = model_path() else {
            eprintln!("bone_map_covers_all_model_bones: no model — skipping");
            return;
        };
        let model = LoadedModel::load(&path).expect("load model");
        let unmapped = model.unmapped_bones();
        assert!(
            unmapped.is_empty(),
            "bones map to no physics part: {unmapped:?}"
        );
    }
}
